"""rename yandex_price to special_price and use datetime.now instead of datetime.utcnow

Revision ID: 830bbec595d4
Revises: 0f9664a9267d
Create Date: 2024-05-17 00:38:47.006059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '830bbec595d4'
down_revision: Union[str, None] = '0f9664a9267d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_prices', sa.Column('special_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('product_prices', 'yandex_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_prices', sa.Column('yandex_price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('product_prices', 'special_price')
    # ### end Alembic commands ###
